services:
  postgres:
    image: postgres:16-alpine3.20
    container_name: train_postgres
    restart: no
    environment:
      - POSTGRES_USER=train_user
      - POSTGRES_PASSWORD=train_password
      - POSTGRES_DB=TrainBookingServiceDb
    ports:
      - '5432:5432'
    volumes: 
        - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: lobby_mongodb
    restart: no
    environment:
      MONGO_INITDB_ROOT_USERNAME: lobby_user
      MONGO_INITDB_ROOT_PASSWORD: lobby_password
    ports:
      - '9876:27017'
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: no
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: rabbit_password
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  postgres-data:
  mongo-data:
  rabbitmq-data:
