services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      PROXY_TIMEOUT: ${PROXY_TIMEOUT}
      WINDOW_SIZE: ${WINDOW_SIZE}
      MAX_CONCURRENT_REQUESTS: ${MAX_CONCURRENT_REQUESTS}
    ports:
      - '7070:8080'
    networks:
      - micro-network
    depends_on:
      - train_booking_service
      - lobby_service

  service_discovery:
    build:
      context: ./service_discovery
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      REDIS_HOST: ${REDIS_SUPLIMENTARY_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - '6060:8080'
      - '50051:50051'
    networks:
      - micro-network
    depends_on:
      - redis_discovery

  redis_discovery:
    image: redis:latest
    restart: no
    ports:
      - "${REDIS_SUPLIMENTARY_PORT}:${REDIS_PORT}"
    networks:
      - micro-network
    volumes:
      - redis_discovery-data:/data

  train_booking_service:
    build:
      context: ./train_booking_service
      dockerfile: Dockerfile  
    restart: on-failure
    environment:
      DATABASE_URL: ${TRAIN_DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    ports:
      - '8000:8000'
    networks:
      - micro-network
    depends_on:
      - postgres_trains
      - redis_cache
      - rabbitmq

  lobby_service:
    build:
      context: ./lobby_service
      dockerfile: Dockerfile  
    restart: on-failure
    environment:
      DATABASE_URL: ${LOBBY_DATABASE_URL}
      BOOKINGS_SERVICE_URL: ${BOOKINGS_SERVICE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    ports:
      - '9000:8000'
    networks:
      - micro-network
    depends_on:
      - postgres_lobbies
      - redis_cache
      - rabbitmq

  postgres_trains:
    image: postgres:16-alpine3.20
    restart: no
    environment:
      - POSTGRES_USER=${TRAIN_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TRAIN_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TRAIN_POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - micro-network
    volumes: 
        - postgres_trains-data:/var/lib/postgresql/data

  postgres_lobbies:
    image: postgres:16-alpine3.20
    restart: no
    environment:
      - POSTGRES_USER=${LOBBY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${LOBBY_POSTGRES_PASSWORD}
      - POSTGRES_DB=${LOBBY_POSTGRES_DB}
    ports:
      - '5433:5432'
    networks:
      - micro-network
    volumes: 
        - postgres_lobbies-data:/var/lib/postgresql/data
  
  redis_cache:
    image: redis:latest
    restart: no
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - micro-network
    volumes:
      - redis_cache-data:/data

  rabbitmq:
    image: rabbitmq:management
    restart: no
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - micro-network

volumes:
  redis_discovery-data:
  postgres_trains-data:
  postgres_lobbies-data:
  redis_cache-data:

networks:
  micro-network:
    driver: bridge
