services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - '7070:80'
    networks:
      - micro-network
    depends_on:
      - train_booking_service
      - lobby_service
    volumes:
      - gateway-data:/app

  train_booking_service:
    build:
      context: ./train_booking_service
      dockerfile: Dockerfile  
    restart: on-failure
    environment:
      DATABASE_URL: ${TRAIN_DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    ports:
      - '8000:8000'
    networks:
      - micro-network
    depends_on:
      - postgres_trains
      - redis_cache
      - rabbitmq
    volumes:
      - train_booking_service-data:/app

  lobby_service:
    build:
      context: ./lobby_service
      dockerfile: Dockerfile  
    restart: on-failure
    environment:
      DATABASE_URL: ${LOBBY_DATABASE_URL}
      BOOKINGS_SERVICE_URL: ${BOOKINGS_SERVICE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    ports:
      - '9000:8000'
    networks:
      - micro-network
    depends_on:
      - postgres_lobbies
      - redis_cache
      - rabbitmq
    volumes:
      - lobby_service-data:/app

  postgres_trains:
    image: postgres:16-alpine3.20
    restart: no
    environment:
      - POSTGRES_USER=${TRAIN_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TRAIN_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TRAIN_POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - micro-network
    volumes: 
        - postgres_trains-data:/var/lib/postgresql/data

  postgres_lobbies:
    image: postgres:16-alpine3.20
    restart: no
    environment:
      - POSTGRES_USER=${LOBBY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${LOBBY_POSTGRES_PASSWORD}
      - POSTGRES_DB=${LOBBY_POSTGRES_DB}
    ports:
      - '5433:5432'
    networks:
      - micro-network
    volumes: 
        - postgres_lobbies-data:/var/lib/postgresql/data
  
  redis_cache:
    image: redis:latest
    restart: no
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - micro-network
    volumes:
      - redis_cache-data:/data

  rabbitmq:
    image: rabbitmq:management
    restart: no
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - micro-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  gateway-data:
  train_booking_service-data:
  lobby_service-data:
  postgres_trains-data:
  postgres_lobbies-data:
  redis_cache-data:
  rabbitmq-data:

networks:
  micro-network:
    driver: bridge
