services:
  db:
    image: postgres:16-alpine3.20
    restart: no
    environment:
      - POSTGRES_USER=train_user
      - POSTGRES_PASSWORD=train_password
      - POSTGRES_DB=TrainBookingServiceDb
    ports:
      - '5432:5432'
    volumes: 
        - db-data:/var/lib/postgresql/data

volumes:
  db-data: