# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service_discovery.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service_discovery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17service_discovery.proto\x12\x11service_discovery\"E\n\x16ServiceRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\";\n\x17ServiceRegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2u\n\x10ServiceDiscovery\x12\x61\n\x08Register\x12).service_discovery.ServiceRegisterRequest\x1a*.service_discovery.ServiceRegisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_discovery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVICEREGISTERREQUEST']._serialized_start=46
  _globals['_SERVICEREGISTERREQUEST']._serialized_end=115
  _globals['_SERVICEREGISTERRESPONSE']._serialized_start=117
  _globals['_SERVICEREGISTERRESPONSE']._serialized_end=176
  _globals['_SERVICEDISCOVERY']._serialized_start=178
  _globals['_SERVICEDISCOVERY']._serialized_end=295
# @@protoc_insertion_point(module_scope)
